package com.dtd.letsbet.model;

public enum NotificationType {
	REQUEST_ACCEPTED,
	REQUEST_DECLINED,
	INCOMING_BET,
	BET_WON,
	BET_LOOSE,
	FRIEND_REQUEST_ACCEPTED,
	FRIEND_REQUEST_DECLINED,
	GAMEPLAY_STATUS_CHANGE
}